/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import Controlador.SistemaVentasControlador;
/**
 *
 * @author alex_
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private SistemaVentasControlador ctrl;
    private boolean esAdmin;
    public VentanaPrincipal(SistemaVentasControlador ctrl, boolean esAdmin) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.ctrl = ctrl;
        this.esAdmin = esAdmin;
        
        configurarMenuSegunRol();
    }
    private void configurarMenuSegunRol(){
        if(esAdmin){
            btnComprar.setVisible(false);
            btnMisCompras.setVisible(false);
            btnPanelAdmin.setVisible(true);
        }else{
            btnPanelAdmin.setVisible(false);
            btnComprar.setVisible(true);
            btnMisCompras.setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel2 = new javax.swing.JLabel();
        btnVerZonas = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnMisCompras = new javax.swing.JButton();
        btnPanelAdmin = new javax.swing.JButton();
        btnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("¡ BIENVENIDO, SELECCIONA LA OPCIÓN A EJECUTAR!");

        btnVerZonas.setText("Ver zonas y precios");
        btnVerZonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerZonasActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar Entradas");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnMisCompras.setText("Mi Historial y Puntos");
        btnMisCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisComprasActionPerformed(evt);
            }
        });

        btnPanelAdmin.setText("Panel de Administración");
        btnPanelAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPanelAdminActionPerformed(evt);
            }
        });

        btnCerrarSesion.setText("Cerrar Sesión");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 69, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPanelAdmin)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnMisCompras)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVerZonas)
                            .addComponent(btnComprar))))
                .addGap(138, 138, 138))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnCerrarSesion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(btnComprar)))
                .addGap(18, 18, 18)
                .addComponent(btnVerZonas)
                .addGap(18, 18, 18)
                .addComponent(btnMisCompras)
                .addGap(18, 18, 18)
                .addComponent(btnPanelAdmin)
                .addGap(28, 28, 28)
                .addComponent(btnCerrarSesion)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Tu chamba Aniee");
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        VistaLogin login = new VistaLogin(this.ctrl);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnPanelAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPanelAdminActionPerformed
        VistaPanelAdmin panelAdmin = new VistaPanelAdmin(this, this.ctrl);
        panelAdmin.setVisible(true);
    }//GEN-LAST:event_btnPanelAdminActionPerformed

    private void btnVerZonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerZonasActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, "Tu chamba Nathan");
    }//GEN-LAST:event_btnVerZonasActionPerformed

    private void btnMisComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisComprasActionPerformed
        VistaHistorialCliente historial = new VistaHistorialCliente(this, this.ctrl);
        historial.setVisible(true);
    }//GEN-LAST:event_btnMisComprasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnMisCompras;
    private javax.swing.JButton btnPanelAdmin;
    private javax.swing.JButton btnVerZonas;
    private javax.swing.JLabel jLabel2;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
